log "/var/log/bird.log" all;

define LOCAL_ASN=<vultr_asn>;
define VULTR_PWD="<vultr_password>";
define VULTR_HOP=2;
define LOCAL_IPV4=<vultr_machine_ipv4>;
define LOCAL_IPV6=<vultr_machine_ipv6>;

router id LOCAL_IPV4;

include "global_asn.conf";
include "global_func.conf";
# include "cn_asn.conf";

protocol device {
    scan time 5;
}

protocol kernel kernel4 {
  ipv4 {
    import none;
    export filter{
        if source = RTS_DEVICE then reject;
        if proto = "vultr_4" then reject;
        accept;
        };
    };
  };

protocol kernel kernel6 {
  ipv6 {
    import none;
    export filter {
        if source = RTS_DEVICE then reject;
        if proto = "vultr_6" then reject;
        reject;
    };
  };
}

protocol static static_bgp_neighbor_v4 {
    ipv4;
    route 169.254.169.254/32 via <machine_ipv4_route>%<NIC>;
}
protocol static static_bgp_neighbor_v6 {
    ipv6;
    route 2001:19f0:ffff::1/128 via <machine_ipv6_route>%<NIC>;
}


template bgp vultr_bgp {
    local as LOCAL_ASN;
    graceful restart on;
    multihop VULTR_HOP;
    password VULTR_PWD;
}

function preprocess_vultr_bgp_path() {
    bgp_path.delete(BOGON_ASNS);
    # 20473为vultr的对外公开ASN
    if bgp_path.first != 20473 then bgp_path.prepend(20473);
}

protocol bgp vultr_4 from vultr_bgp
{
    neighbor 169.254.169.254 as 64515;
    source address LOCAL_IPV4;
    ipv4 {
        import filter {
            if net_len_too_long() then reject;
            preprocess_vultr_bgp_path();
            accept;
        };
        export none;
    };
}
protocol bgp vultr_6 from vultr_bgp
{
    neighbor 2001:19f0:ffff::1 as 64515;
    source address LOCAL_IPV6;
    ipv6 {
        import filter {
            if net_len_too_long() then reject;
            preprocess_vultr_bgp_path();
            accept;
        };
        export none;
    };
}

